### PR TITLE
🌱 Use bookworm slim to build sushy-tools image

### PR DESCRIPTION
**Pull request by elfosardo**
It should reduce the final size of the image from 1.2GB to 500MB

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

From 1.18G to 0.57G, good finding.

**Comment by elfosardo** [comment]
if it works :D
CI doesn't seem very happy

**Comment by elfosardo** [comment]
removing gcc at the end saves us even more bringing the image down to 350 MB

**Comment by tuminoid** [comment]
> removing gcc at the end saves us even more bringing the image down to 350 MB

Seems to work without it indeed. 342MB on my machine, even better.

**Review by kashifest — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
