### PR TITLE
Disable Fastrack

### PR DESCRIPTION
**Pull request by derekhiggins**
A but with fasttrack that was recently fixed, still seems
to be present
https://review.opendev.org/#/c/702011/1

### CODE REVIEW

**Comment by derekhiggins** [comment]
/hold
need to double check this in upstream ironic before merging

**Comment by elfosardo** [comment]
that's weird, the latest centos8 RDO train openstack-ironic package has the fix
was this tested with the latest image with centos8 as base ?

**Comment by derekhiggins** [comment]
> that's weird, the latest centos8 RDO train openstack-ironic package has the fix
> was this tested with the latest image with centos8 as base ?

I seem to have the fix so I'm guessing there is a problem with it

```
[root@localhost core]# podman logs ironic-conductor | grep ERROR | grep agent_url
2020-01-16 12:24:23.229 1 ERROR ironic.conductor.utils [req-1d6b2359-8f70-407d-b9d7-3c4a9e850453 - - - - -] Node 0d134800-01ca-40e8-ab29-3330524dc61d failed deploy step {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}. Error: Agent driver requires agent_url in driver_internal_info: ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
2020-01-16 12:24:23.277 1 ERROR ironic.conductor.utils [req-40bb5744-8d8e-4b8f-874e-64efcf14df15 - - - - -] Node 88bd79f5-c7d0-4656-902c-6c79498a94c2 failed deploy step {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}. Error: Agent driver requires agent_url in driver_internal_info: ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
2020-01-16 12:24:23.403 1 ERROR ironic.conductor.utils [req-5fffaa67-b1c8-4243-b55b-4591bb3b1721 - - - - -] Node f5aa6af3-225f-4eab-8db4-2be8acb4e401 failed deploy step {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}. Error: Agent driver requires agent_url in driver_internal_info: ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
2020-01-16 12:24:23.406 1 ERROR ironic.conductor.task_manager [req-1d6b2359-8f70-407d-b9d7-3c4a9e850453 - - - - -] Node 0d134800-01ca-40e8-ab29-3330524dc61d moved to provision state "deploy failed" from state "deploying"; target provision state is "active": ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
2020-01-16 12:24:23.483 1 ERROR ironic.conductor.task_manager [req-40bb5744-8d8e-4b8f-874e-64efcf14df15 - - - - -] Node 88bd79f5-c7d0-4656-902c-6c79498a94c2 moved to provision state "deploy failed" from state "deploying"; target provision state is "active": ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
2020-01-16 12:24:23.508 1 ERROR ironic.conductor.task_manager [req-5fffaa67-b1c8-4243-b55b-4591bb3b1721 - - - - -] Node f5aa6af3-225f-4eab-8db4-2be8acb4e401 moved to provision state "deploy failed" from state "deploying"; target provision state is "active": ironic_lib.exception.IronicException: Agent driver requires agent_url in driver_internal_info
[root@localhost core]# 
[root@localhost core]# 
[root@localhost core]# 
[root@localhost core]# podman exec -it ironic-conductor bash 
[root@localhost /]# cat /etc/redhat-release 
CentOS Linux release 8.1.1911 (Core) 
[root@localhost /]# grep -B 3 -A 3 fast_track /usr/lib/python3.6/site-packages/ironic/conductor/manager.py 
        driver_internal_info.pop('cleaning_reboot', None)
        driver_internal_info.pop('cleaning_polling', None)
        # Remove agent_url
        if not utils.fast_track_able(task):
            driver_internal_info.pop('agent_url', None)
        node.driver_internal_info = driver_internal_info
        node.save()
[root@localhost /]# rpm -qa | grep ironic-con
openstack-ironic-conductor-13.0.3-0.20200110204733.7f1f79a.el8.noarch
[root@localhost /]# 

```

**Comment by juliakreger** [comment]
@derekhiggins The only thing I can think is that you've got an error in last_error, or cleaning is exiting an unexpected path. If I can get the complete log for the deploy and the node output, then that would help me figure out what is going on. I double checked the path and I don't see where else it could be exiting.. so I'm a little confused.

**Comment by juliakreger** [comment]
Hey @derekhiggins, give https://review.opendev.org/703160  a try.

**Comment by maelk** [comment]
This was already disabled in Baremetal Operator. The fast track option is set to false in the configmap. This is probably not needed.

**Comment by derekhiggins** [comment]
> Hey @derekhiggins, give https://review.opendev.org/703160 a try.

Thanks, Ya, its fixed/working now, the the container images needs to be rebuilt to pick up the new ironic...

**Pull request closed without merging**
