### PR TITLE
✨ Expose individual external URL variables

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

These variables are set based on IRONIC_EXTERNAL_IP by default. In some cases it makes sense to use different IPs for them. This commit also adds these variables to the readme along with IRONIC_EXTERNAL_IP, which was previously undocumented.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by elfosardo** [comment]
there are a lot of unrelated changes ot README.md
would it be possible to move them to another PR?

**Comment by lentzi90** [comment]
> there are a lot of unrelated changes ot README.md would it be possible to move them to another PR?

Possibly, but they are mostly whitespace/line-length related to please the linter. The only other thing I did in the readme was add these:

```md
- `PROVISIONING_IP` - the specific IP to use (instead of calculating it based on
  the `PROVISIONING_INTERFACE`)
- `IRONIC_EXTERNAL_IP` - Optional external IP if Ironic is not accessible on
  `PROVISIONING_IP`.
- `IRONIC_EXTERNAL_CALLBACK_URL` - Override Ironic's external callback URL.
  Defaults to use `IRONIC_EXTERNAL_IP` if available.
- `IRONIC_EXTERNAL_HTTP_URL` - Override Ironic's external http URL. Defaults to
  use `IRONIC_EXTERNAL_IP` if available.
- `IRONIC_INSPECTOR_CALLBACK_ENDPOINT_OVERRIDE` - Override Inspector's callback
  URL. Defaults to use `IRONIC_EXTERNAL_IP` if available.
```

The `PROVISIONING_IP` is third from the top, the rest are at the bottom. `PROVISIONING_IP` and `IRONIC_EXTERNAL_IP` were already exposed variables but undocumented.

**Comment by lentzi90** [comment]
Alright, it worked! Now without the reformatting of the readme :slightly_smiling_face:

**Review by Rozzii — APPROVED** [review]
/lgtm
Thanks this will help with deployment customization.

**Pull request merged**
