### PR TITLE
:sparkles: relocate ironic-client to this repository

### PR DESCRIPTION
**Pull request by tuminoid**
Relocate ironic-client image from ironic-client repo, which will be archived.

Ref: https://github.com/metal3-io/ironic-client/issues/30

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

This is not tested by e2e. We need to add some simple job that builds the image on PRs, not only after merges. This was not present in ironic-client repo either, so it will be done in separate PR.

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
