### PR TITLE
Remove iptables filters from ironic containers

### PR DESCRIPTION
**Pull request by derekhiggins**
We don't appear to need these, infact they output
errors on container startup...

### CODE REVIEW

**Comment by derekhiggins** [comment]
/hold
will run through ci once this merges https://github.com/openshift-metal3/dev-scripts/pull/826

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1215/

**Comment by russellb** [comment]
Once it's working and you remove the hold, /lgtm

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1242/

**Comment by derekhiggins** [comment]
/lgtm
ci failed in 12_csr_hack.sh

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1327/

**Pull request merged**
