### PR TITLE
Revert "Wait for expected number of drivers starting API"

### PR DESCRIPTION
**Pull request by dtantsur**
The root cause has been fixed in Ironic.

This reverts commit 3c8acf4f3b26a5055362b091aec2dfeb8b06d89d.

### CODE REVIEW

**Comment by andfasano** [comment]
> The root cause has been fixed in Ironic.
> 
> This reverts commit [3c8acf4](https://github.com/metal3-io/ironic-image/commit/3c8acf4f3b26a5055362b091aec2dfeb8b06d89d).

@dtantsur in which version this problem has been fixed? Does it mean that also [this readiness BMO check](https://github.com/metal3-io/baremetal-operator/blob/4a7f34ff2f0af32333ec483a809ac92c98f7f937/pkg/provisioner/ironic/dependencies.go#L64-L88) could be removed?

**Comment by dtantsur** [comment]
> Does it mean that also this readiness BMO check could be removed?

No, the BMO check is actually correct. This check here was introduced to work around the bug fixed by https://review.opendev.org/c/openstack/ironic/+/764911.

**Comment by andfasano** [comment]
> > Does it mean that also this readiness BMO check could be removed?
> 
> No, the BMO check is actually correct. This check here was introduced to work around the bug fixed by https://review.opendev.org/c/openstack/ironic/+/764911.

Ack, thanks

**Pull request merged**
