### PR TITLE
:bug: Pin setuptools and pin upper-constraints

### PR DESCRIPTION
**Pull request by elfosardo**
Usually the setuptools installed by the system is stable but
a bit too old compared to the packages we use for ironic,
so pinning a more recent version helps avoiding
errors and incompatibilities.

Also pin upper-constraints since we forgot!

### CODE REVIEW

**Comment by tuminoid** [comment]
Oh we had forgotten to pin the requirements, ouch :)

**Review by tuminoid — COMMENTED** [review]
/lgtm

Also mention of upper constrain pinning in the PR title.

**Comment by elfosardo** [comment]
@dtantsur  can you please have a look?

**Pull request merged**
