### PR TITLE
Replace IRONIC_IP in dnsmasq config

### PR DESCRIPTION
**Pull request by maelk**
the variable was not being replaced by sed

### CODE REVIEW

**Comment by hardys** [comment]
lgtm but added the CI label just to be sure - interesting that this didn't result in broken deployments since e.g https://github.com/metal3-io/ironic-image/pull/107/ passed the metal3 CI...

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1344/

**Comment by stbenjam** [comment]
CI failure unrelated.

/lgtm

**Comment by maelk** [comment]
@hardys I think it passed the CI, because we do not use PXE, we use ipxe in the integration tests. there is no error there. If we were using pxe, it would be broken

**Pull request merged**
