### PR TITLE
:seedling: Update pip version

### PR DESCRIPTION
**Pull request by elfosardo**
Also update pip install commands where needed from `pip3` to `pythib3 -m pip`

### CODE REVIEW

**Comment by elfosardo** [comment]
/test metal3-centos-e2e-integration-test-main
mmmm....

**Comment by mboukhalfa** [comment]
> Also update pip install commands where needed

What has changed ?

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by elfosardo** [comment]
> > Also update pip install commands where needed
> 
> What has changed ?

@mboukhalfa  using the pip command directly is deprecated, in general the recommended command syntax is "python -m pip"

**Pull request merged**
