### PR TITLE
Switch to Centos 8 Stream base image

### PR DESCRIPTION
**Pull request by elfosardo**
Images taken from https://www.centos.org/centos-stream/

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Comment by elfosardo** [comment]
related to https://github.com/metal3-io/metal3-dev-env/issues/671

**Review by namnx228 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
That is weird, both tests have run exactly for `2h52min`, whereas timeout set for integration tests is `1h30min`. Re-triggering to see what went wrong. 

/test-integration
/test-centos-integration

**Comment by elfosardo** [comment]
giving it another try, locally seems working
/test-centos-integration

**Comment by elfosardo** [comment]
it seems we're moving back to centos 8.3 for the time being https://github.com/metal3-io/metal3-dev-env/pull/704
/hold

**Comment by furkatgofurov7** [comment]
@elfosardo I think we can move forward with this change, since we took back CentOS Stream again into use in metal3-dev-env?
[metal3-dev-env#707](https://github.com/metal3-io/metal3-dev-env/pull/707)

**Review by furkatgofurov7 — COMMENTED** [review]
@elfosardo hi! This seems to be failing even though we switched to Stream in m3-dev-env, also a question, should we update vbmc [Dockerfile](https://github.com/metal3-io/ironic-image/blob/master/resources/vbmc/Dockerfile#L1-L4) too?

**Comment by elfosardo** [comment]
> @elfosardo hi! This seems to be failing even though we switched to Stream in m3-dev-env, also a question, should we update vbmc [Dockerfile](https://github.com/metal3-io/ironic-image/blob/master/resources/vbmc/Dockerfile#L1-L4) too?

I can't reproduce the failure locally :/
yes, we should change the vbmc dockerfile too, I thought to do that in a different patch though

**Comment by elfosardo** [comment]
the issue seems related to the connection to mariadb
this is from the ironic-api logs
[Wed Jul 07 10:44:53.011685 2021] [wsgi:error] [pid 112:tid 140611176912640] [remote 172.17.0.16:55960] 2021-07-07 10:44:53.009 112 WARNING oslo_db.sqlalchemy.engines [req-aa2c23c9-eee8-42bc-ac2a-42a7b3fbf51a - - - - -] SQL connection failed. 10 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m

**Comment by elfosardo** [comment]
seems like we're using different versions of oslo-db between ubuntu and centos
ubuntu has a more recent one (9.1.0) which probably fixes the issue with the db connection

**Comment by elfosardo** [comment]
@fmuyassarov we're now getting the same version of oslo-db (9.1.0-0.20210617075225.be2cc6a.el8) in the integration tests, centos based is still failing, so at this point looks like something's wrong with the certificate maybe?

**Comment by fmuyassarov** [comment]
I will try to debug it from within the test VM now
/test-centos-integration

**Comment by fmuyassarov** [comment]
So, I just did some kubectling and realized that no CAPI and CAPM3 machines were created. By looking at Ironic-api I saw the following
```
[Wed Jul 14 13:28:02.402507 2021] [wsgi:debug] [pid 117:tid 140496754751232] src/server/mod_wsgi.c(2433): [remote 172.17.0.16:39524] mod_wsgi (pid=117): Failed to write response data: Broken pipe.
[Wed Jul 14 13:28:02.405078 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:02.403 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 10 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:28:06.886619 2021] [ssl:debug] [pid 118:tid 140496684930816] ssl_engine_io.c(1112): [client 172.17.0.16:42942] AH02001: Connection closed to child 10 with standard shutdown (server 172.22.0.2:443)
[Wed Jul 14 13:28:06.887331 2021] [ssl:debug] [pid 118:tid 140496684930816] ssl_engine_io.c(1112): [client 172.17.0.16:42944] AH02001: Connection closed to child 10 with standard shutdown (server 172.22.0.2:443)
[Wed Jul 14 13:28:12.423890 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:12.422 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 9 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:28:22.439027 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:22.437 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 8 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:28:31.885853 2021] [ssl:info] [pid 214:tid 140496424888064] [client 172.17.0.16:43804] AH01964: Connection to child 215 established (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.886122 2021] [ssl:debug] [pid 214:tid 140496424888064] ssl_engine_kernel.c(2420): [client 172.17.0.16:43804] AH02645: Server name not provided via TLS extension (using default/first virtual host)
[Wed Jul 14 13:28:31.889031 2021] [ssl:debug] [pid 214:tid 140496424888064] ssl_engine_kernel.c(2266): [client 172.17.0.16:43804] AH02041: Protocol: TLSv1.3, Cipher: TLS_AES_128_GCM_SHA256 (128/128 bits)
[Wed Jul 14 13:28:31.891766 2021] [ssl:debug] [pid 214:tid 140496424888064] ssl_engine_kernel.c(422): [client 172.17.0.16:43804] AH02034: Initial (No.1) HTTPS request received for child 215 (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.891916 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.891971 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:31.892095 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.892199 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:31.895223 2021] [ssl:info] [pid 119:tid 140496684930816] [client 172.17.0.16:43806] AH01964: Connection to child 74 established (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.895798 2021] [ssl:debug] [pid 119:tid 140496684930816] ssl_engine_kernel.c(2420): [client 172.17.0.16:43806] AH02645: Server name not provided via TLS extension (using default/first virtual host)
[Wed Jul 14 13:28:31.900893 2021] [ssl:debug] [pid 119:tid 140496684930816] ssl_engine_kernel.c(2266): [client 172.17.0.16:43806] AH02041: Protocol: TLSv1.3, Cipher: TLS_AES_128_GCM_SHA256 (128/128 bits)
[Wed Jul 14 13:28:31.901160 2021] [ssl:debug] [pid 119:tid 140496684930816] ssl_engine_kernel.c(422): [client 172.17.0.16:43806] AH02034: Initial (No.1) HTTPS request received for child 74 (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.901396 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.901550 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:31.901808 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.901920 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of <RequireAny>: granted
172.17.0.16 - - [14/Jul/2021:13:28:31 +0000] "GET /v1 HTTP/1.1" 200 2199 "-" "gophercloud/2.0.0"
[Wed Jul 14 13:28:31.904570 2021] [ssl:debug] [pid 214:tid 140496424888064] ssl_engine_kernel.c(422): [client 172.17.0.16:43804] AH02034: Subsequent (No.2) HTTPS request received for child 215 (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.904849 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.905054 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:31.905232 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.905469 2021] [authz_core:debug] [pid 214:tid 140496424888064] mod_authz_core.c(820): [client 172.17.0.16:43804] AH01626: authorization result of <RequireAny>: granted
172.17.0.16 - - [14/Jul/2021:13:28:31 +0000] "GET /v1 HTTP/1.1" 200 2199 "-" "gophercloud/2.0.0"
[Wed Jul 14 13:28:31.915223 2021] [ssl:debug] [pid 119:tid 140496684930816] ssl_engine_kernel.c(422): [client 172.17.0.16:43806] AH02034: Subsequent (No.2) HTTPS request received for child 74 (server 172.22.0.2:443)
[Wed Jul 14 13:28:31.915331 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.915506 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:31.915647 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of Require all granted: granted
[Wed Jul 14 13:28:31.915778 2021] [authz_core:debug] [pid 119:tid 140496684930816] mod_authz_core.c(820): [client 172.17.0.16:43806] AH01626: authorization result of <RequireAny>: granted
[Wed Jul 14 13:28:32.456103 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:32.454 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 7 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:28:33.648134 2021] [ssl:info] [pid 119:tid 140496726894336] [client 172.22.0.2:38978] AH01964: Connection to child 69 established (server 172.22.0.2:443)
[Wed Jul 14 13:28:33.648528 2021] [ssl:debug] [pid 119:tid 140496726894336] ssl_engine_kernel.c(2420): [client 172.22.0.2:38978] AH02645: Server name not provided via TLS extension (using default/first virtual host)
[Wed Jul 14 13:28:33.651536 2021] [ssl:info] [pid 119:tid 140496726894336] [client 172.22.0.2:38978] AH02008: SSL library error 1 in handshake (server 172.22.0.2:443)
[Wed Jul 14 13:28:33.651923 2021] [ssl:info] [pid 119:tid 140496726894336] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Wed Jul 14 13:28:33.652142 2021] [ssl:info] [pid 119:tid 140496726894336] [client 172.22.0.2:38978] AH01998: Connection closed to child 69 with abortive shutdown (server 172.22.0.2:443)
[Wed Jul 14 13:28:42.465782 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:42.464 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 6 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:28:52.475248 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:28:52.474 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 5 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:29:02.490541 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:29:02.489 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 4 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:29:12.507893 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:29:12.506 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 3 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[Wed Jul 14 13:29:22.523327 2021] [wsgi:error] [pid 117:tid 140496788322048] [remote 172.17.0.16:40372] 2021-07-14 13:29:22.522 117 WARNING oslo_db.sqlalchemy.engines [req-a2e990f2-792b-4564-859a-da0ab25825db - - - - -] SQL connection failed. 2 attempts left.: oslo_db.exception.DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897))")\x1b[00m
[airshipci@ci-test-vm-20210714124746-fwbt ~]$ =
```
```
[airshipci@ci-test-vm-20210714124746-fwbt metal3]$ kubectl get bmh -n metal3
NAME     STATE   CONSUMER   ONLINE   ERROR
node-0                      true     
node-1                      true     


[airshipci@ci-test-vm-20210714124746-fwbt metal3]$ kubectl get machine -A
No resources found
[airshipci@ci-test-vm-20210714124746-fwbt metal3]$ kubectl get metal3machine -A
No resources found

```

**Comment by elfosardo** [comment]
@fmuyassarov I saw the same errors as wrote in one of my precedent comments, I thought it was because of a regression in the oslo-db package but now we're using the same version between ubuntu and centos integration tests, so I believe there's something wrong on how we deal with the certificate

**Comment by namnx228** [comment]
@elfosardo `/certs/ca/mariadb/tls.crt` is a self-signed certificate, and it is used as a CA certificate. 
The other cert that was generated in @fmuyassarov dev-env is the certificate issued by the CA, and it should looks different from the CA certificate. So, mariadb uses the second cert for the TLS handshake, and ironic or other clients use the first cert to verify if they are talking to the right mariadb. In my opinion, the self-signed certificate should be fine without CN as long as the client can trust and use its public key for verification.

**Comment by elfosardo** [comment]
@namnx228 it doesn't look like that cert is used as CA according to mariadb configuration:
`--ssl=on --ssl_cert=/certs/mariadb/tls.crt --ssl_key=/certs/mariadb/tls.key`
the correct option for the CA cert should be ssl_ca

**Comment by namnx228** [comment]
@elfosardo The one used for --ssl_cert is `/certs/mariadb/tls.crt` (without `ca`) while the self-signed one is `/certs/ca/mariadb/tls.crt` (with `ca`)

**Comment by elfosardo** [comment]
> @elfosardo The one used for --ssl_cert is `/certs/mariadb/tls.crt` (without `ca`) while the self-signed one is `/certs/ca/mariadb/tls.crt` (with `ca`). The one without ca should have CN.

@namnx228 what I mean is that the CA cert is not defined anywhere in mariadb, or at least I can't see it
the problem here is that ironic is using /certs/ca/mariadb/tls.crt to try to establish an ssl connection to mariadb and it's failing because the cert is self-signed and because it doesn't have any Common Name
the `ERROR 2026 (HY000): SSL connection error: self signed certificate`  message looks clear enough

**Comment by namnx228** [comment]
@elfosardo Yes, I agree that the culprit here is that there is a issue with the CA certificate of Mariadb. I just wonder why we didn't see it in Centos before. 
Actually, I also saw a problem with TLS CA certificate before in the CI when we switch from Centos to Centos stream in metal3-dev-env, and the solution was to disable SELinux which is enforced by default. Maybe it can also solve this problem?

**Comment by namnx228** [comment]
CommonName has been added to Ironic and Mariadb certs in this PR: https://github.com/metal3-io/baremetal-operator/pull/951
Let's see if it can solve the issue of this PR.
/test-integration
/test-centos-integration

**Comment by elfosardo** [comment]
@namnx228 thanks for taking care of that! Let's see if it fixes the issue
I haven't checked but it could be due to an upgrade in mariadb packaged version in centos stream

**Pull request merged**
