### PR TITLE
[DO NOT MERGE] Connection debugging

### PR DESCRIPTION
**Pull request by dtantsur**
See https://github.com/metal3-io/cluster-api-provider-metal3/issues/1082

### CODE REVIEW

**Comment by dtantsur** [comment]
Of course it does not fail when I need it to :(

/test-ubuntu-integration-main

**Comment by dtantsur** [comment]
/test-ubuntu-integration-main

Some infra-related problem, not the failure I'm looking for.

**Comment by Sunnatillo** [comment]
Hey @dtantsur, I have created [PR in metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/pull/1290) including this patch.
I was able to reproduce the issue with your changes.

https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_centos/19/
https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_ubuntu/9/

**Comment by Sunnatillo** [comment]
@dtantsur, do you need a live env where issue happened?

**Comment by dtantsur** [comment]
@Sunnatillo I'm afraid it won't help me much: I don't know where to look. Also one of my team members has been able to reproduce the problem.

/test-centos-integration-main
/test-ubuntu-integration-main

**Pull request closed without merging**
