### PR TITLE
:seedling: Remove dnf config-manager after its use

### PR DESCRIPTION
**Pull request by elfosardo**
We don't really need it in the final image

### CODE REVIEW

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-main  metal3-ubuntu-e2e-integration-test-main 

Ironic is built in e2e, so it is a good test (we don't have separate build test anymore)

**Comment by elfosardo** [comment]
/test metal3-centos-e2e-integration-test-main
issue with CI ?

**Comment by tuminoid** [comment]
> /test metal3-centos-e2e-integration-test-main issue with CI ?

Just a random network flake. It is amazing how they happen in such basic operations such as git clone or download a binary :(

**Comment by tuminoid** [comment]
I'm starting to think this has an effect on the failures (doesn't make sense tho), CI is quite stable otherwise....

**Comment by elfosardo** [comment]
> I'm starting to think this has an effect on the failures (doesn't make sense tho), CI is quite stable otherwise....

I'll retest once more

**Comment by elfosardo** [comment]
@tuminoid this is really weird, the only thing I can think about is some dependencies being removed that are needed later
I'm testing CI here https://github.com/metal3-io/ironic-image/pull/527 just to verify it

**Comment by elfosardo** [comment]
/test metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

bash: line 1: minikube: command not found

**Pull request merged**
