### PR TITLE
Enable redfish driver

### PR DESCRIPTION
**Pull request by jan-est**
We want to use Redfish so we need to enable the redfish driver in ironic.conf

### CODE REVIEW

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1091/

**Comment by russellb** [comment]
This will need a rebase after merging #74, sorry

**Comment by maelk** [comment]
@russellb done, thank you

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1093/

**Pull request merged**
