### PR TITLE
Update ironic.conf to include 'idrac-wsman' and 'idrac' in enabled_raid_interfaces.

### PR DESCRIPTION
**Pull request by nasirkamal**
Enable 'idrac' and 'idrac-wsman' interface for RAID configuration.

### CODE REVIEW

**Comment by demonCoder95** [comment]
@maelk can you give this one a /test-integration as well? It's the same as the bios interface patch I've created.

**Comment by demonCoder95** [comment]
@dhellmann can you do this one as well? thanks! :)

**Comment by maelk** [comment]
It looks like there is an issue with this PR. Jenkins is unable to find its correct parent repository, hence to merge it properly. Even Github says "Unknown repository" and links to a 404. Can you please fix the issue ?

**Comment by nasirkamal** [comment]
I am creating another PR, because I accidentally deleted the repository from where I initiated the PR.

**Pull request closed without merging**
