### PR TITLE
Enable the custom-deploy deploy interface

### PR DESCRIPTION
**Pull request by dtantsur**
Required for https://github.com/metal3-io/metal3-docs/pull/180.

### CODE REVIEW

**Review by iurygregory — APPROVED** [review]

**Review by elfosardo — APPROVED** [review]

**Comment by dtantsur** [comment]
/approve

I'm taking Riccardo's lgtm as approval since he's on the way to approvers already (per https://github.com/metal3-io/ironic-image/pull/274)

**Pull request merged**
