### PR TITLE
🌱 Update build status on release-23.1

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR is updating the build status after changing jenkins jobs naming

### CODE REVIEW

**Comment by tuminoid** [comment]
/close
23.1 is now configured.

**Comment by mboukhalfa** [comment]
> /close 23.1 is now configured.

I think the PR changes is still valid to the release since the badges there still not updated

**Comment by mboukhalfa** [comment]
> /close 23.1 is now configured.

I think the PR changes is still valid to the release since the badges there still not updated

**Comment by tuminoid** [comment]
> > /close 23.1 is now configured.
> 
> I think the PR changes is still valid to the release since the badges there still not updated

Oh sorry, my bad.

**Comment by tuminoid** [comment]
/override  metal3-centos-e2e-integration-test-release-1-5 metal3-ubuntu-e2e-integration-test-release-1-5
Not relevant for a readme update.

**Pull request merged**
