### PR TITLE
:seedling: add pull request template and workflow to verify it

### PR DESCRIPTION
**Pull request by tuminoid**
Add pull request template, and a Github workflow to verify the PR contents, like verifying the change type emoji in title. This supports creation of release notes for future releases.

### CODE REVIEW

**Comment by tuminoid** [comment]
Ping release team.
/cc @adilGhaffarDev @elfosardo @smoshiur1237

**Comment by tuminoid** [comment]
/override test-centos-integration-main 
/override test-ubuntu-integration-main 
Irrelevant for actions.

**Review by smoshiur1237 — COMMENTED** [review]
Thanks for adding this which will help us during the release. It looks good from my side.
LGTM

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
