### PR TITLE
:book: add OpenSSF Scorecard badge to README

### PR DESCRIPTION
**Pull request by tuminoid**
Add OpenSSF Scorecard badge to README. It is checked by the CLOmonitor and lowers our score by not having it. We have worked to improve the scores, so we can display the score as well.

### CODE REVIEW

**Comment by tuminoid** [comment]
Scorecard is not generated for ironic-image by openssf for some reason, but it is also a code-lite repo in CLO, so it is NOT monitored for this repo.

/hold
until I've checked why the scoring is not done for this.

**Comment by tuminoid** [comment]
Adding ironic-image to the OpenSSF Scorecard project list, so it can display this badge: https://github.com/ossf/scorecard/pull/3783

**Comment by tuminoid** [comment]
> Adding ironic-image to the OpenSSF Scorecard project list, so it can display this badge: [ossf/scorecard#3783](https://github.com/ossf/scorecard/pull/3783)

Merged. The badge will be available sometime next week as the run cycle is one week and it is unknown which weekday will do our repos.

**Comment by tuminoid** [comment]
/unhold
The scorecard badge is now valid as project is included in securityscorecard.dev scans.

**Comment by tuminoid** [comment]
/override test-centos-integration-main test-ubuntu-integration-main 
Its readme change.

**Comment by tuminoid** [comment]
/retitle :book: add OpenSSF Scorecard badge to README

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by kashifest — APPROVED** [review]
/lgtm

**Pull request merged**
