### PR TITLE
:bug: improve upper constraint handling

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
 - Provides a default value for the UPPER_CONSTRAINT docker file argument
 - Changes the prepare-image.sh logic to check the actual size of the upper constraint file and not the presence of it.

Background of this change is that it has been noticed that on release branches during image building the "pinned" upper constraint file is not picked up rather pulled from upstream OpenStack because of a lack of default argument value during image building.

### CODE REVIEW

**Comment by Rozzii** [comment]
If this gets merged I will cherry pick this to other branches.

**Review by tuminoid — COMMENTED** [review]
/lgtm

This must be backported to release branches as well, where it actually matters.

**Comment by tuminoid** [comment]
@Rozzii will make manual cherry-picks to all maintained release branches.

We also need to consider should we make patch release after fix is merged, as this might/will change the Python dependencies quite drastically. @elfosardo thoughts?

**Pull request merged**
