### PR TITLE
🌱 Update for release-26.0

### PR DESCRIPTION
**Pull request by dtantsur**
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by dtantsur** [comment]
Sanity check

/test markdownlint
/test metal3-centos-e2e-integration-test-release-1-8
/test metal3-ubuntu-e2e-integration-test-release-1-8
/test shellcheck

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-release-1-8
/test metal3-ubuntu-e2e-integration-test-release-1-8
CI for 1.8 should be fine now.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
OK, it worked.

/cc @iurygregory @derekhiggins 
You might need to self-approve/push.

**Pull request merged**
