### PR TITLE
Add support for Fujitsu driver irmc

### PR DESCRIPTION
**Pull request by tiendc**
This patch adds hardware type "irmc" and hardware interface "irmc"
for inspect, management, power interfaces in ironic.conf.

#49
Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>

### CODE REVIEW

**Comment by russellb** [comment]
@dtantsur @juliakreger can one of you ack this?

**Comment by dtantsur** [comment]
Actually, don't you want to add one of the iRMC boot interfaces to the list?

**Comment by tiendc** [comment]
> Actually, don't you want to add one of the iRMC boot interfaces to the list?

iRMC driver in baremetal-operator currently uses 'pxe' as boot interface [1]. So at the moment the current configuration of boot interfaces is enough for us.

[1] https://github.com/metal3-io/baremetal-operator/blob/master/pkg/bmc/irmc.go#L54

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1092/

**Pull request merged**
