### PR TITLE
Promote Iury to approvers, remove Stephen

### PR DESCRIPTION
**Pull request by dtantsur**
Iury is the Ironic PTL (project team lead) and has been consistently
reviewing ironic-image changes in his reviewer role.

Stephen has moved to another role.

### CODE REVIEW

**Comment by elfosardo** [comment]
we need https://github.com/metal3-io/ironic-image/pull/354 to fix the ironic image build

**Review by elfosardo — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
> we need #354 to fix the ironic image build

354 is merged now.

/test-v1b1-ubuntu-integration

**Comment by derekhiggins** [comment]
lgtm 
holding back the / to all others to vote

**Comment by dtantsur** [comment]
We don't really need everyone to vote, the email thread was conclusive enough with a simple majority.

**Comment by derekhiggins** [comment]
/lgtm

> We don't really need everyone to vote, the email thread was conclusive enough with a simple majority.
ack

**Pull request merged**
