### PR TITLE
Use current instead of current-tripleo to get the CI fix

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by Rozzii** [comment]
Could you please point me to the CI failure that you have experienced?

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by dtantsur** [comment]
CI failures can be seen in https://github.com/metal3-io/ironic-image/pull/389

**Comment by Rozzii** [comment]
Lets reopen this I think we are seeing this issue still
/reopen

**Comment by Rozzii** [comment]
example: https://jenkins.nordix.org/job/metal3_ironic_image_main_integration_test_ubuntu/41/console

**Comment by Rozzii** [comment]
/hold
I am not sure, this issue comes and goes.

**Comment by dtantsur** [comment]
https://jenkins.nordix.org/job/metal3_ironic_image_main_integration_test_ubuntu/41/console is a failure to reach RDO repos, this change won't help IMO

**Comment by Rozzii** [comment]
> https://jenkins.nordix.org/job/metal3_ironic_image_main_integration_test_ubuntu/41/console is a failure to reach RDO repos, this change won't help IMO

Yes, I agree in the meantime the issue has been solved .
/close

**Pull request closed without merging**
