### PR TITLE
🌱 improve bash syntax in prepare-image

### PR DESCRIPTION
**Pull request by elfosardo**
Follow up to https://github.com/metal3-io/ironic-image/pull/585

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/retitle :seedling: Improve bash syntax in prepare-image
PR title checker didn't retrigger on manual change?

/lgtm

**Comment by tuminoid** [comment]
/retitle 🌱 improve bash syntax in prepare-image

Another try...

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
