### PR TITLE
⚠️ Completely remove support for ironic-inspector

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
This looks good! Is it ready?

**Comment by dtantsur** [comment]
> This looks good! Is it ready?

I wanted to wait for https://github.com/metal3-io/ironic-image/pull/482 to merge before causing a lot of conflicts for it. Now it's ready to go!

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
