### PR TITLE
add clomonitor badge to README

### PR DESCRIPTION
**Pull request by tuminoid**
Add CLOMonitor badge to README as ironic-image is one of the included repos that is checked (starting tomorrow).

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-centos-integration-main
/override test-ubuntu-integration-main
Not relevant here, plus the ubuntu one is broken anyways. (Ci team is on it)

**Pull request merged**
