### PR TITLE
🐛Fix CPU burning on ironic-log-watch when no ramdisk file is present

### LINKED ISSUE #547: ironic-log-watch: CPU at full capacity in case of no ramdisk file present
In the ironic-log-watch container when no ramdisk file is present in /shared/log/ironic/deploy directory an infinite loop lead cpu to be at full capacity all the time.

### PR DESCRIPTION
**Pull request by blallau**
Use inotifywait instead of an infinite loop.

Fixes #547

### CODE REVIEW

**Comment by tuminoid** [comment]
We have https://github.com/metal3-io/ironic-image/pull/540 already addressing similar issue, can you collaborate on that PR?

**Comment by tuminoid** [comment]
Please fix shellcheck issues, preferably use curlys around variables as well, and when linting is green, trigger integration tests.

**Comment by tuminoid** [comment]
> /retest

Retest won't run tests that are not run in the first place. 
/test metal3-centos-e2e-integration-test-main  metal3-ubuntu-e2e-integration-test-main

**Comment by tuminoid** [comment]
Can you rebase, so the fix we have merged is included. Otherwise CI won't work.

**Comment by tuminoid** [comment]
> Can you rebase, so the fix we have merged is included. Otherwise CI won't work.

The official fix is in, so this should work now.
/retest

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by derekhiggins** [comment]
/approve
thanks

**Pull request merged**
